### ISSUE TITLE
Where is data stored?

### ISSUE THREAD

**Issue by martino-amped** [idibidiart/AllSeeingEye#4]
Hi I was wondering AllSeeingEye stores the data. It may be useful for viewing and backuping  data out of Chrome.

Thanks.

**Comment by idibidiart** [comment]
It's stored in IndexedDB, which is a NoSQL database available in all modern browsers. If you go to chrome://extensions URL in Chrome and enable Developer Mode you may pack the extension and install it yourself from the Github source. Once it's installed, you can click on "Inspect views: background page" link under the extension on that page and it will bring up the debugger console. If you click on Resources and click on IndexedDB you will see your data stored in indexedDB format, but you can still read it. I'm not sure where Chrome stores IndexedDB on the file system and it's different on Mac vs Windows. I guess a Backup feature would be good, and it's possible to do, so I'll close this issue and open a new one just for that. Thanks.

**Comment by martino-amped** [comment]
Ok! Thanks a lot for the reply.
